project:
  type: website
  output-dir: docs


execute:
  freeze: auto

website:
  title: "Online Marketing 2"
  navbar:
    left:
      - href: index.qmd
        text: Home

  sidebar:
    background: "#ffffff"
    logo: "images/logo.png"
    pinned: true
    align: center


    style: docked
    search: true
    collapse-level: 2
    contents:
      - section: "Course information"
        contents:
          - href: syllabus.qmd
            text: Syllabus  
          - href: index.qmd
            text: Semester Overview
          - href: weeks.qmd
            text: Weekly Overview
          - href: project-description.qmd
            text: Project Description       

format:
  html:
    toc: false
    theme: cosmo
    css: custom.scss
    code-copy: true
    highlight-style: github-dark
    code-overflow: wrap
    author-meta: "Jan Kirenz"
    callout-appearance: simple
    include-in-header:
      - text: |
          <script src="password.js"></script>